config/routes.rb
Rails.application.routes.draw do
  get 'books', to: 'books#index'
  root 'books#index'

  get 'books/new'
  post 'books', to: 'books#create'

  get 'books/:id', to: 'books#show', as: 'book'
  
  get 'books/:id/edit', to: 'books#edit', as: 'book_edit'
  patch 'books/:id', to: 'books#update'

  delete 'books/:id', to: 'books#destroy' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    enum status: [:borrowed, :on_shelf]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, only: %i[show edit update destroy]
  before_action :set_selects, only: %i[new edit create update]

  def index
    @q = Book.ransack(params[:q])
    @books = @q.result(distinct: true)

  end

  def new
    @book = Book.new
  end

  def show
  end

  def edit
  end

  def update

    respond_to do |format|
      if @book.update(book_params)
        format.html {redirect_to @book, notice: "Libro editado"}
      else
        format.html {render :edit}
      end
    end
  end

  def create
    @book = Book.create(book_params)
    respond_to do |format|
      if @book.save
        format.html {redirect_to @book, notice: "Libro guardado exitosamente"}
      else
        format.html {render :new}
      end
    end

  end

  def destroy
    @book.destroy
    redirect_to root_path, notice: 'libro borrado exitosamente.'
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :status, :borrowing_date, :return_date)
  end
  def set_book
     @book = Book.find(params[:id])
  end
  def set_selects
    @statuses = Book.statuses.keys
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, "Titulo" %>
    <%= f.text_field :title, placeholder: "ingresa un titulo", class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :author, "Autor" %>
    <%= f.text_field :author, placeholder: "ingresa un Autor", class: 'form-control' %>
  </div>


 <div class="form-group">
    <%= f.label :status, "Estado" %>
    <%= f.select :status, options_for_select(@statuses),{:include_blank => true}, class: 'form-control' %>
  </div>


   <div class="form-group">
    <%= f.label :borrowing_date, "Fecha de prestamos" %>
    <%= f.date_field :borrowing_date, class: 'form-control' %>
  </div>

   <div class="form-group">
    <%= f.label :return_date,"Fecha de Devolucion" %>
    <%= f.date_field :return_date, class: 'form-control' %>
  </div>



  <div class = 'actions'>
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <%= render 'form', book: @book %>
</div>

app/views/books/index.html.erb
<div class="container">

<%= render 'shared/navbar' %>
<p id="notice"><%= notice %></p>
<h1>Books</h1>
<table class="table table-dark">
    <thead>
        <tr>
        <th><%= sort_link(@q, :title, 'Titulo') %></th>
        <th>Author</th>
        <th>Status</th>
        <th>Borrowing date</th>
        <th>Return date</th>
        <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.status %></td>
        <td><%= book.borrowing_date %></td>
        <td><%= book.return_date %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', book_edit_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'quieres eliminar este librito ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Book', books_new_path %>

</div>

app/views/books/new.html.erb
<div class="container">
  <%= render 'form', book: @book %>
</div>

app/views/books/show.html.erb
<div class="container pt-4">

  <p id="notice"><%= notice %></p>
  <p>
    <strong>Title:</strong>
    <%= @book.title %>
  </p>
  <p>
    <strong>Author:</strong>
    <%= @book.author %>
  </p>
  <p>
    <strong>Status:</strong>
    <%= @book.status %>
  </p>
  <p>
    <strong>Borrowing date:</strong>
    <%= @book.borrowing_date %>
  </p>
  <p>
    <strong>Return date:</strong>
    <%= @book.return_date %>
  </p>

  <%= link_to 'Ir al root', root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand"> Books</a>
  <%= search_form_for @q do |f|%>
    <div class="form-group form-inline my-2 my-lg-0">
      <%= f.select :status_eq, options_for_select(Book.statuses, @q.status_eq), {}, {class: 'form-control mx-2'} %>
      <%= f.submit 'Filtrar', class: 'btn btn-primary' %>
    </div>
  <% end %>
</nav>